config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'registrations#new'
  post '/signup', to: 'registrations#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  match '/upvote_post/:id', to: 'posts#upvote', via: %i[get post], as: 'upvote_post'
  match '/downvote_post/:id', to: 'posts#downvote', via: %i[get post], as: 'downvote_post'

  match '/upvote_comment/:id', to: 'comments#upvote', via: %i[get post], as: 'upvote_comment'
  match '/downvote_comment/:id', to: 'comments#downvote', via: %i[get post], as: 'downvote_comment'

  match '/save_post/:id', to: 'posts#save', via: %i[get post], as: 'save_post'

  match '/save_comment/:id', to: 'comments#save', via: %i[get post], as: 'save_comment'

  match '/archive_post/:id', to: 'posts#archive', via: %i[get post], as: 'archive_post'

  match '/publish_post/:id', to: 'posts#publish', via: %i[get post], as: 'publish_post'

  resources :comments do
    member do
      post :reply
    end
  end

  resources :posts do
    resources :comments, only: %i[create]
  end

  resources :users, param: :username, only: %i[show edit update]

  get '/search', to: 'search#index'

  get '/communities/list', to: 'communities#list'

  resources :communities, param: :name, only: %i[show index create]
  get '/new_community', to: 'communities#new'
  post '/new_community', to: 'communties#create'

  match '/join_community/:name', to: 'communities#join', via: %i[get post], as: 'join_community'

  match '/follow_user/:username', to: 'users#follow', via: %i[get post], as: 'follower'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true,
                       format: { with: /[a-zA-Z0-9_]{1,20}/, message: 'Invalid Username' }
  validates :display_name, presence: true, length: { maximum: 40 }
  validates :email, presence: true, uniqueness: true,
                    format: { with: URI::MailTo::EMAIL_REGEXP, message: 'Invalid Email' }
  validates :bio, length: { maximum: 200 }

  has_many :posts
  has_many :comments
  has_many :post_votes, dependent: :destroy
  has_many :comment_votes, dependent: :destroy
  has_many :post_saves, class_name: 'PostSave', dependent: :destroy

  has_many :followers, class_name: 'Follower', foreign_key: :user_id
  has_many :following, class_name: 'Follower', foreign_key: :follower_id
  has_many :joined_communities, class_name: 'CommunityMember', foreign_key: :user_id
  has_many :pinned_posts, class_name: 'Post', foreign_key: :pin_owner_id

  has_many :owned_communities, class_name: 'Community', foreign_key: :owner_id

  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end

  before_create do
    self.display_name = username
  end

  def self.search(query)
    where('username LIKE ? OR display_name LIKE ?', "%#{query}%", "%#{query}%")
  end

  def login
    update(last_online: Time.now, is_online: true)
  end

  def logout
    update(last_online: Time.now, is_online: false)
  end

  def drafts
    posts.where(status: 'draft')
  end

  def editable?
    Current.user == self
  end

  def saved_posts
    Post.where(id: post_saves.pluck(:post_id))
  end

  def saved?(post)
    post_saves.find_by(post: post)
  end

  def upvoted?(post)
    post_votes.find_by(post: post, isUpvote: true)
  end

  def downvoted?(post)
    post_votes.find_by(post: post, isUpvote: false)
  end

  def upvoted_comment?(comment)
    comment_votes.find_by(comment: comment, isUpvote: true)
  end

  def downvoted_comment?(comment)
    comment_votes.find_by(comment: comment, isUpvote: false)
  end

  def following?(user)
    following.find_by(user: user)
  end

  def follow(user)
    following.create(user: user)
  end

  def unfollow(user)
    following.find_by(user: user).destroy
  end

  def followed_by?(user)
    followers.find_by(follower: user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: %i[edit update follow]

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(username: params[:username])
    @followers = @user.followers.pluck(:follower_id).map { |id| User.find(id) }
    @tab = params[:tab]

    valid_tabs = %w[overview posts comments saved drafts]
    private_tabs = %w[saved drafts]
    fullwidth_tabs = %w[posts comments]
    @tab = 'overview' unless valid_tabs.include?(@tab)
    @fullwidth = fullwidth_tabs.include?(@tab)

    if @user.nil?
      # TODO: Add a 404 page, add JSON response, 404 status code
      redirect_to root_path, alert: 'User not found'
      return
    end

    return if @user == Current.user
    return unless private_tabs.include?(@tab)

    redirect_to user_path(@user.username), alert: 'You are not authorized to view this page'
    nil
  end

  def edit
    @user = User.find_by(username: params[:username])
    @followers = @user.followers.pluck(:follower_id).map { |id| User.find(id) }
    @tab = params[:tab]
    valid_tabs = %w[overview posts comments saved drafts]
    fullwidth_tabs = %w[posts comments]
    @tab = 'overview' unless valid_tabs.include?(@tab)
    @fullwidth = fullwidth_tabs.include?(@tab)

    unless @user.editable?
      redirect_to user_path(@user.username), alert: 'You are not
      authorized to view this page'
      return
    end

    render :show, locals: { editable: true }
  end

  def update
    @user = User.find(params[:username].to_i) # TODO: Fix this

    unless @user == Current.user
      # TODO: Add JSON response
      redirect_to user_path(@user.username), alert: 'You are not
      authorized to view this page'
      return
    end

    if params[:user][:avatar]
      @user.avatar.purge
      @user.avatar.attach(params[:user][:avatar])
    end

    if @user.update!(user_params)
      # TODO: Add JSON response
      redirect_to user_path(@user.username), notice: 'User updated
      successfully'
    else
      render :show, status: :unprocessable_entity
    end
  end

  def follow
    if Current.user.nil?
      # TODO: Add JSON response
      redirect_to request.referrer || root_path, alert: 'You must be logged in to perform that action'
      return
    end

    @user = User.find_by(username: params[:username])
    if Current.user.following?(@user)
      Current.user.unfollow(@user)
    else
      Current.user.follow(@user)
    end

    redirect_to user_path(@user.username)
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :display_name, :email, :password, :password_confirmation, :bio,
                                 :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_tab_link(link_text, user, tab = link_text.downcase)
    link_path = user_path user.username, tab: tab

    class_name = 'active' if current_page?(link_path)
    class_name = 'active' if params[:tab].blank? && tab == 'overview'

    content_tag(:li, class: class_name) do
      link_to link_text, link_path
    end
  end
end

app/views/users/_comments.html.erb
<% unless @user.comments.exists? %>
  <p>There are no comments yet.</p>
<% end %>
<% @user.comments.each do |comment| %>
  <%= render 'comments/comment_compact', comment: comment %>
<% end %>

app/views/users/_drafts.html.erb
<% unless @user.drafts.exists? %>
  <article class="padded">There are no drafts yet.</article>
<% end %>
<% @user.drafts.order(created_at: :desc).each do |draft| %>
  <%= render "posts/post_draft", post: draft %>
<% end %>

app/views/users/_edit_sidebar.html.erb
<aside>
  <%= form_with model: user do |f| %>
    <article class="user-profile edit-profile" data-controller="user">
      <div class="user-profile__banner">
        <div class="user-avatar__wrapper" data-target="user.avatarWrapper">
          <%= f.label :avatar do %>
            <%= user_avatar_img @user, "medium", { target: "user.avatar" } %>
            <%= f.file_field :avatar, data: { action: 'user#updateAvatar', target: 'user.avatarInput' } %>
          <% end %>
        </div>
      </div>
      <div class="field-wrapper">
        <%= f.label :display_name %>
        <%= f.text_field :display_name %>
        <%= f.label :username %>
        <%= f.text_field :username %>
        <%= f.label :bio %>
        <%= f.text_area :bio %>
        <%= f.submit 'Save Changes' %>
      </div>
    </article>
  <% end %>
  <article class="titled">
    <h1>Followers</h1>
    <% unless user.followers.exists? %>
      <p>No followers yet!</p>
    <% else %>
      <ul>
        <% @followers.each do |follower| %>
          <%= render "users/list_item", user: follower %>
        <% end %>
      </ul>
    <% end %>
  </article>
</aside>

app/views/users/_list_item.html.erb
<li class="user-item"><%= link_to user.display_name, user_path(user.username) %></li>

app/views/users/_nav.html.erb
<nav class="nav-user">
  <ul>
    <%= user_tab_link "overview", user%>
    <%= user_tab_link "posts", user %>
    <%= user_tab_link "comments", user %>
    <% if Current.user == user %>
      <%= user_tab_link "saved", user %>
      <%= user_tab_link "drafts", user %>
    <% end %>
  </ul>
</nav>

app/views/users/_overview.erb
<% unless @user.posts.exists? || @user.comments.exists? %>
  <p>This user has no posts or comments.</p>
<% end %>
<% @user.posts.order(created_at: :desc).each do |post| %>
  <% if post.published? %>
    <%= render post %>
  <% end%>
<% end %>

app/views/users/_posts.html.erb
<% unless @user.posts.exists? %>
  <p>There are no posts yet.</p>
<% end %>
<% @user.posts.order(created_at: :desc).each do |post| %>
  <%= render "posts/post_compact", post: post %>
<% end %>

app/views/users/_saved.html.erb
<% unless @user.saved_posts.exists? %>
  <p>There are no saved posts yet.</p>
<% end %>
<% @user.saved_posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>

app/views/users/_sidebar.html.erb
<aside>
  <article class="user-profile">
    <div class="user-profile__banner">
      <% if @user.editable? %>
        <div class="user-avatar__wrapper" data-target="user.avatarWrapper">
          <%= user_avatar_img @user, "medium", { target: "user.avatar" } %>
        </div>
      <% else %>
        <%= user_avatar(@user,"medium") %>
      <% end %>
    </div>
    <div class="user-profile__username">
      <h2><%= @user.display_name %></h2>
      <%= link_to "u/#{user.username}", user_path(@user.username) %>
      <p class="online <%= 'green' if @user.is_online %>">
        <% if @user.is_online %>
          • online
        <% else %>
          Last seen <%= time_ago_in_words(@user.last_online) %> ago
        <% end %>
      </p>
    </div>
    <% unless @user.bio.blank? %>
      <p><%= @user.bio %></p>
    <% end %>
    <div class="user-profile__stats">
      <p>
        <b>Joined</b>
        <i class="fa-solid fa-right-to-bracket"></i>
        <%= time_ago_in_words(@user.created_at) %> ago
      </p>
      <p>
        <b>Posts</b>
        <%= icon("fa-regular","file-lines") %> <%= @user.posts.count %>
      </p>
      <p>
        <b>Comments</b>
        <%= icon("fa-regular","comment") %> <%= @user.comments.count %>
      </p>
    </div>
    <%= follow_button @user %>
    <% if @user.editable? %>
      <%= link_to edit_user_path(@user.username), class:"edit-profile-link" do %>
        <%= icon("fa","pen") %> Edit Profile
      <% end %>
    <% end %>
  </article>
  <article class="titled">
    <h1>Followers</h1>
    <% unless @user.followers.exists? %>
      <p>No followers yet!</p>
    <% else %>
      <ul>
        <% @followers.each do |follower| %>
          <%= render "users/list_item", user: follower %>
        <% end %>
      </ul>
    <% end %>
  </article>
  <% if @user.owned_communities %>
    <article class="titled">
      <h1>Created Communities</h1>
      <ul>
        <% @user.owned_communities.each do |community| %>
          <%= render "communities/list_item", community: community %>
        <% end %>
      </ul>
    </article>
  <% end %>
</aside>

app/views/users/_user.html.erb
<%= render 'shared/list_item', 
  class_name: 'user',
  avatar: user_avatar(user),
  top_text: user.display_name,
  bottom_text: link_to("u/#{user.username}", user_path(user.username)),
  button: follow_button(user)
 %>

app/views/users/index.html.erb
<h1>Users</h1>
<% unless @users.exists? %>
  <p>There are no users yet.</p>
<% else %>
  <p>Total number of Users: <%= User.count %></p>
  <ul class="users">
    <% @users.each do |user| %>
      <li class="user-list-item">
        <%= link_to user.username, user_path(user) %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/users/show.html.erb
<main>
  <% content_for :header do %>
    <%= render "nav", user: @user %>
  <% end %>
  <% if local_assigns[:editable] %>
    <%= render "edit_sidebar", user: @user %>
  <% else %>
    <%= render "sidebar", user: @user %>
  <% end %>
  <section class="<%= "fullwidth" if @fullwidth %>">
    <%= render @tab %>
  </section>
</main>