config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'registrations#new'
  post '/signup', to: 'registrations#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  match '/upvote_post/:id', to: 'posts#upvote', via: %i[get post], as: 'upvote_post'
  match '/downvote_post/:id', to: 'posts#downvote', via: %i[get post], as: 'downvote_post'

  match '/upvote_comment/:id', to: 'comments#upvote', via: %i[get post], as: 'upvote_comment'
  match '/downvote_comment/:id', to: 'comments#downvote', via: %i[get post], as: 'downvote_comment'

  match '/save_post/:id', to: 'posts#save', via: %i[get post], as: 'save_post'

  match '/save_comment/:id', to: 'comments#save', via: %i[get post], as: 'save_comment'

  match '/archive_post/:id', to: 'posts#archive', via: %i[get post], as: 'archive_post'

  match '/publish_post/:id', to: 'posts#publish', via: %i[get post], as: 'publish_post'

  resources :comments do
    member do
      post :reply
    end
  end

  resources :posts do
    resources :comments, only: %i[create]
  end

  resources :users, param: :username, only: %i[show edit update]

  get '/search', to: 'search#index'

  get '/communities/list', to: 'communities#list'

  resources :communities, param: :name, only: %i[show index create]
  get '/new_community', to: 'communities#new'
  post '/new_community', to: 'communties#create'

  match '/join_community/:name', to: 'communities#join', via: %i[get post], as: 'join_community'

  match '/follow_user/:username', to: 'users#follow', via: %i[get post], as: 'follower'
end

app/models/post.rb
class Post < ApplicationRecord
  include Votable
  include Savable
  include Pinable

  validate :url_must_exist, if: :will_save_change_to_url?
  before_save :create_link_preview, if: :will_save_change_to_url?

  belongs_to :user
  belongs_to :community, optional: true
  belongs_to :link, dependent: :destroy, optional: true

  has_many :votes, class_name: 'PostVote', dependent: :destroy
  has_many :saves, class_name: 'PostSave', dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :pin_owner, class_name: 'User', optional: true

  has_many_attached :media do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end

  validates :title, presence: true, length: { maximum: 100 }
  validates :url, format: URI::DEFAULT_PARSER.make_regexp(%w[http https]), presence: true, if: :type_link?

  validates :body, presence: true, if: :type_text?
  validates :media, presence: true, if: :type_media?

  enum :status, { draft: 0, published: 1, archived: 2 }
  enum :post_type, { text: 0, media: 1, link: 2 }, prefix: 'type'

  # -- scopes ---
  default_scope { published.order(created_at: :desc) }

  # -- static methods ---
  def self.update_link_previews
    Post.where(post_type: 'link').each(&:update_link_preview)
  end

  def self.search(query)
    where('title LIKE ?', "%#{query}%")
  end

  # -- callbacks ---

  def url_must_exist
    return unless type_link?

    begin
      LinkThumbnailer.generate(url)
    rescue URI::InvalidURIError, LinkThumbnailer::BadUriFormat
      # errors.add(:url, 'is not a valid URL')
    rescue OpenSSL::SSL::SSLError
      errors.add(:url, 'is not a valid URL')
    rescue LinkThumbnailer::HTTPError
      errors.add(:url, 'does not exist')
    end
  end

  def create_link_preview(save = false)
    return unless type_link?

    link_obj = Link.find_or_create_by(url: url)
    if save
      update(link: link_obj)
    else
      self.link = link_obj
    end
  end

  def update_link_preview
    return unless type_link?

    link = Link.find_or_create_by(url: url) if link.nil?
    link.create_link_preview
  end

  # --- getters ---
  def title
    if archived?
      'Archived Post'
    else
      read_attribute(:title)
    end
  end

  def body
    if archived?
      'This post has been archived.'
    else
      read_attribute(:body)
    end
  end

  def archive
    update(status: 'archived')
  end

  def publish
    return unless save

    update(status: 'published', created_at: Time.now)
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = Current.user.id
    if @post.save
      redirect_to root_path, notice: "Successfully created post!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: %i[new create edit update destroy publish]

  def index
    @posts = if params[:sort] == 'top'
               Post.order(score: :desc)
             else
               Post.order(created_at: :desc)
             end

    @active_users = User.joins(:posts).group(:id).order('count(posts.id) desc').limit(10)
    @active_communities = Community.all # for now
  end

  def new
    @communities = Community.all
    @post = Post.new
  end

  def create
    @communities = Community.all
    @post = Post.new(post_params)
    @post.user = Current.user
    @post.community = Community.find(params[:post][:community_id])
    @post.status = 'published'

    if params[:draft]
      @post.status = 'draft'
      @post.save(validate: false)
      redirect_to root_path, notice: 'Successfully created draft!'
    elsif @post.save
      redirect_to post_path(@post), notice: 'Successfully created post!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @communities = Community.all
    @post = Post.find(params[:id])
    redirect_to root_path, alert: 'You can only edit your own posts.' unless @post.user == Current.user

    redirect_to root_path, alert: 'You can only edit draft posts.' unless @post.draft?

    render :new
  end

  def update
    @communities = Community.all
    @post = Post.find(params[:id])

    if @post.user != Current.user
      redirect_to root_path, alert: 'You can only edit your own posts.'
    elsif !@post.draft?
      redirect_to root_path, alert: 'You can only edit draft posts.'
    elsif params[:publish]
      if @post.update(post_params) && @post.publish
        redirect_to post_path(@post), notice: 'Successfully published post!'
      else
        render :new, status: :unprocessable_entity
      end
    elsif params[:draft]
      @post.assign_attributes(post_params)
      @post.save(validate: false)
      redirect_to root_path, notice: 'Successfully updated draft!'
    end
  end

  def destroy
    @post = Post.find(params[:id])

    respond_to do |format|
      if !@post.draft?
        msg = 'You can only delete drafts!'
        format.html { redirect_to root_path, notice: msg }
        format.json { render json: { error: msg } }
      elsif Current.user != @post.user
        msg = 'You can only delete your own posts!'
        format.html { redirect_to root_path, notice: msg }
        format.json { render json: { error: msg } }
      elsif @post.destroy
        msg = 'Post deleted successfully!'
        format.html { redirect_to root_path, notice: msg }
        format.json { render json: { msg: msg } }
      else
        msg = 'Something went wrong!'
        format.html { redirect_to root_path, notice: msg }
        format.json { render json: { error: msg } }
      end
    end
  end

  def publish
    @post = Post.find(params[:id])

    if @post.user != Current.user
      redirect_to root_path, alert: 'You can only publish your own posts.'
    elsif @post.publish
      redirect_to post_path(@post), notice: 'Successfully published post!'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.filter { |c| c.parent_id.nil? }
    @comments = order_comments(@comments)
  end

  def order_comments(comments)
    ordered_comments = []

    comments.sort_by(&:created_at).reverse.each do |comment|
      ordered_comments << comment
      ordered_comments += order_comments(comment.children)
    end

    ordered_comments
  end

  def vote(upvote = true)
    # TODO: Add html response
    render json: { error: 'You must be logged in to vote' }, status: :unauthorized and return unless Current.user

    if Current.user.id == params[:user_id].to_i
      render json: { error: 'You can\'t vote on your own posts' }, status: :bad_request
    end

    @post = Post.find(params[:id])
    @post.score = @post.vote(Current.user, upvote)
    @post.save

    render json: { html: render_post(@post) }
  end

  alias upvote vote

  def downvote
    vote(false)
  end

  def save
    # TODO: Add html response
    render json: { error: 'You must be logged in to save' }, status: :unauthorized and return unless Current.user

    @post = Post.find(params[:id])
    @post.bookmark(Current.user)

    render json: { html: render_post(@post) }
  end

  def archive
    # TODO: Add html response
    @post = Post.find(params[:id])

    if @post.user_id != Current.user&.id
      render json: { error: 'You can only archive your own posts.' }, status: :unauthorized
    else
      @post.update(status: 'archived')

      render json: { html: render_post(@post) }
    end
  end

  def render_post(post)
    partial = 'post'
    params[:variant] && partial += "_#{params[:variant]}"

    render_to_string(partial: partial, locals: { post: post, show_pins: params[:showPin] })
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :url, :community_id, :post_type, media: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  include VoteHelper
  include SaveHelper

  def post_upvote_button(post)
    vote_button(post, true, 'post')
  end

  def post_downvote_button(post)
    vote_button(post, false, 'post')
  end

  def post_save_button(post)
    save_button(post, 'post')
  end

  def archive_button(post)
    return unless Current.user&.id == post.user_id
    return if post.archived?

    content_tag :button, class: 'archive_button', data: { action: 'click->post#archive' } do
      icon('fa', 'box-archive').concat(' Archive')
    end
  end

  def delete_button(post)
    return unless Current.user&.id == post.user_id
    return if post.archived?

    content_tag :button, class: 'delete_button', data: { action: 'click->post#delete' } do
      icon('fa', 'trash-alt').concat(' Delete')
    end
  end

  def tab_button(form, tab, content, checked = false)
    name = %w[text media link][tab]
    checked ||= params[:post][:post_type] == name if params[:post]

    content_tag :label, class: 'tab_button' do
      concat form.radio_button :post_type, name, checked: checked,
                                                 data: { action: 'click->post-form#showTab', tab: tab.to_s }
      concat content
    end
  end
end

app/views/posts/_lightbox.html.erb
<div class="lightbox" data-controller="lightbox">
  <div class="lightbox__content" data-lightbox-target="content">
    <% media.each do |image| %>
      <%= image_tag image %>
    <% end %>
    <% if media.count > 1 %>
      <div class="lightbox__overlay">
        <span class="lightbox__overlay__counter" data-lightbox-target="counter">
          1 of <%= media.count %>
        </span>
        <div class="lightbox__overlay__controls">
          <button class="lightbox__button hidden" data-action="click->lightbox#previous" data-lightbox-target="previous" aria-label"previous">
            <%= icon("fa-solid", "chevron-left") %>
          </button>
          <button class="lightbox__button" data-action="click->lightbox#next" data-lightbox-target="next" aria-label="next">
            <%= icon("fa-solid", "chevron-right") %>
          </button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_new_post.html.erb
<% unless Current.user.nil? %>
  <% 
  community_id ||= nil 
  post = {community_id: community_id} 
  %>
  <article class="padded new-post">
    <%= user_avatar Current.user %>
    <%= link_to new_post_path(post: post), class: "input" do %>
      <%= icon("fa-regular","file-lines") %>
      Create Post
    <% end %>
    <%= link_to icon('fa-regular','image'), new_post_path(post: post.merge!(post_type: 'media')), class:"post-type-button" %>
    <%= link_to icon('fa','link'), new_post_path(post: post.merge!(post_type: 'link')), class:"post-type-button" %>
  </article>
<% end %>

app/views/posts/_post.html.erb
<article class="post" data-id="<%= post.id %>" data-controller="post" data-post-target="wrapper" data-show-pin="<%= local_assigns[:show_pins] %>">
  <div class="post__vote">
    <%= post_upvote_button post %>
    <span class="post__score"><%= post.score %></span>
    <%= post_downvote_button post %>
  </div>
  <div class="post__content">
    <section class="post__head">
      posted by <%= link_to post.user.username, user_path(post.user.username) %> <%= time_ago_in_words post.created_at %> ago
      <% if local_assigns[:show_pins] && post.pinned? %>
        <span class="pin">
          <%= icon("fa-solid", "thumbtack") %>
          Pinned by <%= link_to post.pin_owner.username, user_path(post.pin_owner.username) %>
        </span>
      <% end %>
      <span class="id"><%= link_to "POST##{post.id}", post %></span>
    </section>
    <h3><%= post.title %></h3>
    <% if post.type_media? && !post.archived? %>
      <%= render "posts/lightbox", media: post.media %>
    <% elsif post.type_link? && !post.archived? %>
      <a href="<%= post.url %>"><%= post.url %></a>
      <a href="<%= post.url %>" class="no-underline link-preview">
        <div class="link-preview__thumb">
          <%= image_tag post.link.thumb_src, alt:"#{post.url} thumbnail" %>
        </div>
        <div class="link-preview__main">
          <span class="link-preview__title">
            <%= image_tag post.link.favicon_src, class: "link-preview__favicon", alt: "favicon" %>
            <strong><%= post.link.title %></strong>
          </span>
          <p class="link-preview__description">
            <%= post.link.description %>
          </p>
          <span class="link-preview__host">
            <%= icon("fa","link") %> <%= Addressable::URI.parse(post.url).host %>
          </span>
        </div>
      </a>
    <% else %>
      <p><%= post.body %></p>
    <% end %>
    <section class="post__footer">
      <%= button_to post_path(post), method: :get do %>
        <%= icon("fa-regular", "comment") %>
        <%= post.comments.count %> comments
      <% end %>
      <%= post_save_button post %>
      <%= archive_button post %>
    </section>
  </div>
</article>

app/views/posts/_post_compact.html.erb
  
<article class="post-compact" data-id="<%= post.id %>" data-controller="post" data-post-target="wrapper" data-variant="compact">
  <div class="post__vote">
    <%= post_upvote_button post %>
    <span class="post__score"><%= post.score %></span>
    <%= post_downvote_button post %>
  </div>
  <div class="post__thumb">
    <div class="icon_wrapper">
      <% if post.type_media? %>
        <%= image_tag post.media[0].variant(:thumb), alt: post.media[0].name %>
        <% if post.media.count > 1 %>
          <span class="count">
            +<%= post.media.count - 1 %>
          </span>
        <% end %>
      <% elsif post.type_link? %>
        <%= icon("fa","link") %>
      <% else %>
        <%= icon("fa","bars")%>
      <% end %>
    </div>
  </div>
  <div class="post__content">
    <section class="post__head">
      posted by <%= link_to post.user.username, user_path(post.user.username) %> <%= time_ago_in_words post.created_at %> ago
    </section>
    <h3><%= post.title %></h3>
    <section class="post__footer">
      <%= button_to post_path(post), method: :get do %>
        <%= icon("fa-regular", "comment") %>
        <%= post.comments.count %> comments
      <% end %>
      <%= post_save_button post %>
      <%= archive_button post %>
    </section>
  </div>
</article>

app/views/posts/_post_draft.html.erb
<article class="post-compact post-draft post" data-id="<%= post.id %>" data-controller="post" data-post-target="wrapper" data-variant="compact">
  <div class="post__content">
    <section class="post__head">
      Draft created by <%= link_to post.user.username, user_path(post.user.username) %>
      <%= time_ago_in_words post.created_at %> ago
    </section>
    <h3><%= post.title %></h3>
    <section class="post__footer">
      <%= button_to publish_post_path(post), method: :get do %>
        <%= icon("fa-solid", "paper-plane") %>
        Publish
      <% end %>
      <%= button_to edit_post_path(post), method: :get do %>
        <%= icon("fa-solid", "edit") %>
        Edit
      <% end %>
      <%= delete_button post %>
    </section>
  </div>
</article>

app/views/posts/_sidebar.html.erb
  
<aside>
  <article class="titled">
    <h1>About RedditOnRails</h1>
    <p>
      RedditOnRails is a clone of the popular social news website
      <a href="http://www.reddit.com">Reddit</a>. It was built using
      <a href="http://rubyonrails.org">Ruby on Rails</a> and
      <a href="http://www.mysql.com">MySQL</a>.
      The source code is available on
      <a href="https://github.com/CuddlyBunion341/RedditOnRails">GitHub</a>
      under the MIT license.
    </p>
  </article>
  <article class="titled">
    <h1>Active Users</h1>
    <% unless @active_users.exists? %>
      <p>There are no active users.</p>
    <% else %>
      <ul>
        <% @active_users.each do |user| %>
          <%= render "users/list_item", user: user%>
        <% end %>
      </ul>
    <% end %>
  </article>
  <article class="titled">
    <h1>Popular Communities!</h1>
    <% unless @active_communities.exists? %>
      <p>There are no active communities. </p>
    <% else %>
      <ul>
        <% @active_communities.each do |community| %>
          <%= render "communities/list_item", community: community %>
        <% end %>
      </ul>
    <% end %>
  </article>
</aside>

app/views/posts/_sort.html.erb
<article class="padded sort">
  <%= sort_option 'new', 'New', 'newspaper', true %>
  <%= sort_option 'top', 'Popular', 'fire' %>
</article>

app/views/posts/edit.html.erb
<%= render "form" %>

app/views/posts/index.html.erb
<main>
  <%= render "sidebar" %>
  <section id="feed">
    <%= render "new_post" %>
    <%= render "sort" %>
    <% unless @posts.exists? %>
      <p>There are no posts yet.</p>
    <% end %>
    <% @posts.each do |post| %>
      <%= render "post", post: post %>
    <% end %>
  </section>
</main>

app/views/posts/new.html.erb
<div class="form-wrapper post-form" data-controller="post-form">
  <h1>Create Post</h1>
  <div class="errors">
    <% if @post.errors.any? %>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <%= form_with model: @post do |f| %>
    <div class="post-form__tabs" data-post-form-target="tabs">
      <%= tab_button f, 0, icon("fa-regular", "file-lines"), true %>
      <%= tab_button f, 1, icon("fa-regular", "image") %>
      <%= tab_button f, 2, icon("fa", "link") %>
    </div>
    <div class="post-form__main">
      <div class="field">
        <%= render "communities/dropdown" %>
        <%= f.text_field :title, class: error_class(@post, :title), placeholder: "Title" %>
      </div>
      <div class="tab-wrapper" data-post-form-target="wrapper">
        <div id="tab0" class="tab">
          <%= f.text_area :body, class: error_class(@post, :body), placeholder: "Text" %>
        </div>
        <div id="tab1" class="tab hidden">
          <%= f.label :media, class:"upload-region", data: {
            "post-form-target": "dropzone",
            action: "
            drop->post-form#uploadDrop 
            dragover->post-form#uploadDragOver dragleave->post-form#uploadDragLeave"
          } do %>
            Drag and drop media or click
            <%= f.file_field :media, :multiple => true, class: "", data: {
            action: "change->post-form#upload", "post-form-target": "upload"
          } %>
          <% end %>
          <div class="post-form__attachments" data-post-form-target="uploadList">
            <% if @post.media.attached? %>
              <%= @post.media.attachments.inspect %>
              <% @post.media.each do |media| %>
                <picture>
                  <%= image_tag media %>
                  <button class="removebtn" data-file="<%= attachment_identifier(media) %>">✕</button>
                </picture>
              <% end %>
            <% end %>
          </div>
        </div>
        <div id="tab2" class="tab hidden">
          <%= f.text_field :url, placeholder: "Url" %>
        </div>
      </div>
      <div class="actions submit">
        <% if @post.draft? %>
          <%= f.submit 'Publish', name: :publish %>
        <% else %>
          <%= f.submit 'Post' %>
        <% end %>
        <%= f.submit 'Save Draft', name: :draft %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<% if @post.community %>
  <%= render "communities/banner", community: @post.community %>
<% end %>
<main>
  <% if @post.community %>
    <%= render "communities/sidebar", community: @post.community %>
  <% end %>
  <section class="show-post">
    <%= render "post", post: @post %>
    <div class="comments-wrapper">
      <%= render "comments/form" %>
      <% unless @comments.count %>
        <p>No comments yet!</p>
      <% else %>
        <% @comments.each do |comment| %>
          <%= render "comments/comment", comment: comment %>
        <% end %>
      <% end%>
    </div>
  </section>
</main>