config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'registrations#new'
  post '/signup', to: 'registrations#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  match '/upvote_post/:id', to: 'posts#upvote', via: %i[get post], as: 'upvote_post'
  match '/downvote_post/:id', to: 'posts#downvote', via: %i[get post], as: 'downvote_post'

  match '/upvote_comment/:id', to: 'comments#upvote', via: %i[get post], as: 'upvote_comment'
  match '/downvote_comment/:id', to: 'comments#downvote', via: %i[get post], as: 'downvote_comment'

  match '/save_post/:id', to: 'posts#save', via: %i[get post], as: 'save_post'

  match '/save_comment/:id', to: 'comments#save', via: %i[get post], as: 'save_comment'

  match '/archive_post/:id', to: 'posts#archive', via: %i[get post], as: 'archive_post'

  match '/publish_post/:id', to: 'posts#publish', via: %i[get post], as: 'publish_post'

  resources :comments do
    member do
      post :reply
    end
  end

  resources :posts do
    resources :comments, only: %i[create]
  end

  resources :users, param: :username, only: %i[show edit update]

  get '/search', to: 'search#index'

  get '/communities/list', to: 'communities#list'

  resources :communities, param: :name, only: %i[show index create]
  get '/new_community', to: 'communities#new'
  post '/new_community', to: 'communties#create'

  match '/join_community/:name', to: 'communities#join', via: %i[get post], as: 'join_community'

  match '/follow_user/:username', to: 'users#follow', via: %i[get post], as: 'follower'
end

app/views/layouts/_nav.html.erb
<nav class="nav-main">
  <ul>
    <%= nav_link image_tag( "logo.svg"), root_path, "logo" %>
    <li>
      <form action="/search" method="get" class="search-form">
        <input type="text" name="q" placeholder="Search" class="search-form__input" value="<%= params[:q] %>">
        <button type="submit" class="search-form__button">
          <%= icon("fa", "search") %>
        </button>
      </form>
    </li>
    <% if Current.user %>
      <%= nav_link "Create Post", new_post_path %>
      <li class="dropdown">
        <button type="button" class="dropdown__title" href="#">
          <%= @username %>
          <%= icon("fa","chevron-down") %>
        </button>
        <ul class="dropdown__content">
          <%= nav_link "Profile", user_path(@username), '', icon('fa','user') %>
          <%= nav_link "New Community", new_community_path, '',icon('fa','users-line') %>
          <%= nav_button "Logout", logout_path, "logout", icon('fa','arrow-right-from-bracket') %>
        </ul>
      </li>
    <% else %>
      <%= nav_link "SignUp", signup_path, "register-btn" %>
      <%= nav_link "LogIn", login_path, "login-btn" %>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>RedditOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="RedditOnRails is a Reddit clone built with the Ruby on rails technology and is free and open sourced under the MIT license">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="popup">
      <% flash.each do |name, msg| %>
        <div class="flash <%= name %>">
          <%= msg %>
        </div>
      <% end %>
    </div>
    <header>
      <%= render "layouts/nav" %>
      <%= yield :header %>
    </header>
    <%= yield %>
  </body>
</html>